src/core.jl
src/indexing.jl
src/intervals.jl
test/core.jl

Throw `ArgumentError`'s for inavlid arguments

---

README.md
src/intervals.jl
src/search.jl
test/intervals.jl

Just some old uncommitted code I had on my local machine.
Better mixed Interval/Scalar behavior, and faster searchsorted with Ranges.

Minor Intervals cleanup

---

README.md

Remove space to properly close code block and fix mk rendering at http://mbauman.github.io/AxisArrays.jl/latest/

Fix doc markdown for rendering with MkDocs

---

src/AxisArrays.jl
src/core.jl
src/indexing.jl
src/sortedvector.jl
test/REQUIRE
test/core.jl
test/indexing.jl
test/runtests.jl

This is a fairly random collection of changes that I discovered I wanted while porting Images. This does not include #38, but I will likely tackle that within the next day or so (as a separate PR).

Indexing, equality, and dimension-changing operations

---

src/indexing.jl
test/indexing.jl

Split getindex and view apart. Closes #38.

---

src/core.jl

`summary` gets called by `show`. This approach improves modularity.

Move the `show` functionality into `summary`

---

src/core.jl
src/indexing.jl
src/search.jl
test/REQUIRE
test/indexing.jl

Addresses https://github.com/JuliaArrays/AxisArrays.jl/pull/57#discussion_r102583634

Don't extend Base.unsafe_getindex

---

src/core.jl
src/indexing.jl
test/core.jl

Title says it all.
edit - Just not sure I putted the function into the right file.

Added Base.endof method for Axis type

---

src/indexing.jl
test/indexing.jl

Fix CartesianIndex indexing (fix #62 #66)

---

src/core.jl

See https://github.com/JuliaLang/julia/issues/20723 and https://github.com/JuliaLang/julia/pull/20720

Avoid relying on wrong behaviour of map

---

src/core.jl
test/core.jl

https://github.com/JuliaImages/Images.jl/issues/618#issuecomment-291900981

parent(A::AxisArray) = A.data

---

src/indexing.jl

Also add a checkindex method to allow specialization for AxisArrays that wrap specialized structures (like Ranges or RangeArrays).
This has a surprisingly large performance gain in some cases.

Annotate indexing with propagate_inbounds

---

src/core.jl
test/core.jl

* Allow mixed vectors and axes.
* Improve type stability.

AxisArray constructor improvements 

---

test/runtests.jl

I simply put the file includes into their own testsets, which works without changing any of the other test files.

Move tests into testsets

---

src/core.jl
src/sortedvector.jl
test/core.jl

Pulled this standalone commit out of #88

Make axistrait operate on types

---

REQUIRE
src/intervals.jl

Ref https://github.com/JuliaMath/IntervalSets.jl/pull/19.

Move "pirating" promote_rule to IntervalSets

---

src/indexing.jl
src/search.jl
test/indexing.jl
test/search.jl

Rebased version of #90, dropping support for 0.5. CC @mbauman.

Fix interval indexing with offset axes

---

.travis.yml
Project.toml
REQUIRE
docs/Project.toml
docs/make.jl
src/AxisArrays.jl
src/core.jl
src/indexing.jl
test/REQUIRE

Generated with Pkg.jl's gen_project.jl script; edited to add the current AxisArrays version number.
Also modernize the doc build to also use Project.toml; hopefully this is correct, we'll see what CI does.

Upgrade REQUIRE -> Project.toml

---

src/AxisArrays.jl

export AxisMatrix and AxisVector

---

.github/workflows/UnitTest.yml
.gitignore
Project.toml
test/core.jl

Rationale for not testing nightly: https://discourse.julialang.org/t/why-do-packages-run-continuous-integration-tests-on-julia-nightly/101208/3?u=tim.holy
Explanation of the test failure: https://github.com/JuliaLang/julia/issues/50620

Fix broken tests and stop testing nightly
