src/AxisArrays.jl, src/core.jl, test/runtests.jl
This is less of a "work-in-progress" and more of a "something to start discussion" on indexing along axes. Here are feature ideas and other discussion items:
* It'd be nice if other packages can plug in axes types and define ways to index in to them.
* It'd be nice if other packages can declare that an axes type has order, so it can be indexed automatically (sounds like a good use of a Tim-Holy-Trait-Trick.
* It'd be nice to define default indexing for column names and for ranges on time axes. 
* For range indexes on time axes, should it be `A[[from, to],:]`, `A[(from,to),:]`, `A[1s:9s,:]`, or something else?
* What else should we provide by default for indexing?
What's implemented is an `axesindexes` method that tries to generalize indexing along an axes. It should return a UnitRange or …
=> [WIP] Indexing along axes

README.md, src/core.jl
It may be a little early for docs like this given how young the api is, but I drafted something anyway...
Includes docstrings for AxisArray, Axis, and Interval.
We also may want to export and add docstrings for `axes` and `axisnames`.
=> Documentation start

REQUIRE, src/AxisArrays.jl, src/utils.jl
This adds a dependency on Requires.jl. It's a small package that has worked well for me. The main advantage of this code is that it gives us a quick way to plot AxisArrays using Gadfly.
Note that this also requires the development version of DataFrames (I added a feature needed for this).
Note that this causes a ton of warnings when DataFrames and Gadfly are loaded. Most are due to other packages, but some are ambiguity warnings between DataArrays and AxisArrays. DataArrays will probably undergo a lot of change as they convert to some sort of Nullables representation, so I wouldn't worry about these for now. Ambiguity warnings are a PITA. Hopefully, Jeff's type work will fix all that.
=> Add optional utilities for conversion to a DataFrame and for plotting with Gadfly

src/AxisArrays.jl, src/core.jl, src/indexing.jl, src/sortedvector.jl, test/runtests.jl, test/sortedvector.jl
Add a SortedVector type that assumes sorting. Also, change the Dimensional trait to allow duplicates and add indexing by value. A SortedVector{Tuple} allows hierarchical indexing similar to [pandas](http://pandas.pydata.org/) or [data.table](https://github.com/Rdatatable/data.table/wiki). SortedVector hits one of the roadmap (issue #7) bullets.
This also changes axis indexing in two ways:
* Duplicates are allowed. This also helps with Sims.jl because the timescale can have repeated values before and after events. 
* Dimensional axes can now be indexed by value. If there are duplicates, all indexes that match are returned. 
Here are examples of SortedVector and hierarchical indexing:
```julia
v = SortedVector(collect([1., 10., 10:15.]))
A = AxisArray(reshape(1:16, 8, 2), v, [:a, :b]) …
```
=> Add a SortedVector for keyed axis indexes and hierarchical indexing

src/core.jl, test/core.jl
As discussed in https://github.com/mbauman/AxisArrays.jl/issues/22 - allows for `TimeType` dimensional axes.
```julia
julia> using AxisArrays, Base.Dates
julia> A = AxisArray(randn(5,2), Axis{:Timestamp}(now()-Hour(2):Hour(1):now()+Hour(2)), Axis{:Cols}([:A, :B]))
2-dimensional AxisArray{Float64,2,...} with axes:
:Timestamp, 2016-04-25T16:37:22:1 hour:2016-04-25T20:37:22
:Cols, [:A,:B]
And data, a 5x2 Array{Float64,2}:
-0.150798   -0.174845
-0.943928    0.718984
0.0884346   1.13286 
-1.23035    -0.831126
-1.36034     0.402844
```
=> Removed old range ordering check and fixed deprecation warnings

REQUIRE, src/AxisArrays.jl, src/combine.jl, src/core.jl, src/indexing.jl, test/core.jl, test/indexing.jl, test/runtests.jl
This fixes several problems on julia 0.5, including an error thrown by `using AxisArrays`, and eliminates most (but deliberately not all) deprecation warnings.
Left to do: some tests still fail. While I haven't dug deeply, I'm guessing it's a consequence of this package [using `sub` semantics](https://github.com/mbauman/AxisArrays.jl/blob/7674f5d74d0f79271783ca10695559a61b9b0b14/src/indexing.jl#L43-L46) whereas julia master has moved on to `slice` semantics. (This is why I left the sub/slice/view depwarns present, as a TODO reminder.) I recommend that this package follow suit and adopt `slice` (now called `view`) semantics.
This would be a breaking change, so I didn't want to start on it without checking first.
=> Fixes and depwarns for julia 0.5

src/core.jl, test/indexing.jl
If `ax` is an `Axis{name,T}`, then `ax(2)` constructs `Axis{name,Int}(2)` which can be handy for slicing. Ref #33.
=> Simplify slicing with a particular axis. Closes #33

.travis.yml, REQUIRE, src/AxisArrays.jl, src/core.jl, src/indexing.jl, src/intervals.jl, src/search.jl, src/sortedvector.jl, test/indexing.jl, test/intervals.jl, test/sortedvector.jl
The biggest issue here is that this bumps the minimum julia version to 0.5. Anyone have an issue with that? If so, I can see about making IntervalSets.jl work on Julia 0.4.
=> Rebase on IntervalSets

src/core.jl, test/core.jl
Together with the prior addition of permutedims, this closes one of the Roadmap (#7) items.
=> Support (c)transpose

src/indexing.jl, test/indexing.jl
Surprisingly, we still haven't exhausted the number of ways one can combine indexing operations in interesting ways. Here's what I think is a new one:
```jl
julia> using AxisArrays
julia> A = AxisArray(reshape(1:15, 3, 5), :x, :y)
2-dimensional AxisArray{Int64,2,...} with axes:
:x, Base.OneTo(3)
:y, Base.OneTo(5)
And data, a 3×5 Base.ReshapedArray{Int64,2,UnitRange{Int64},Tuple{}}:
1  4  7  10  13
2  5  8  11  14
3  6  9  12  15
julia> axx = A[Axis{:x}]
AxisArrays.Axis{:x,Base.OneTo{Int64}}(Base.OneTo(3))
```
If there's already another way to get the full axis-instance in an inferrable fashion, do let me know. (One that isn't is
```jl
foo{Ax}(A, ::Type{Ax}) = A.axes[axisdim(A, Ax)]
```
)
=> Extract a specific axis via ax = A[Axis{:t}]

src/search.jl, test/REQUIRE, test/indexing.jl, test/readme.jl, test/runtests.jl
For #37. Good spotting that this needed doing.
~~The strategy I took was simply to unpack the Range operations directly. A little inelegant, perhaps, but avoids any risk that `unsafe_getindex` will complain.~~ ~~Won't pass tests without https://github.com/JuliaLang/METADATA.jl/pull/6665.~~
BTW, I am in the process of switching over to [Unitful](https://github.com/ajkeller34/Unitful.jl) for all my units needs. The main holdup is that Base's ranges aren't quite up to snuff, which is basically what my LinSpace PR is all about. See https://github.com/ajkeller34/Unitful.jl/pull/31.
(SIUnits does better in this regard because rolls its own Range type, as a wrapper around `FloatRange` and appending units. I tend to think that a better approach is to generalize the Base ranges so that they can …
=> Test and fix the code in the README

src/core.jl, test/core.jl
This is a bit speculative and perhaps too dicey, but I thought I'd inquire:
```jl
julia> using AxisArrays
julia> axes(rand(3,5))
(Base.OneTo(3),Base.OneTo(5))
```
The motivation is the following: the [ImageMetadata](https://github.com/JuliaImages/ImageMetadata.jl) package defines the successor to the old `Image` type (array + dict) in Images.jl.  When the array inside the `ImageMeta` is an `AxisArray`, it would be nice to give it AxisArray-like properties. However, using that capability "safely" currently requires dispatch:
```jl
foo(A::AbstractArray) = # default action, don't call axes
foo(A::AxisArray) = axes(A)[2]
foo(A::ImageMetaAxis) = axes(data(A))[2]
```
That makes `ImageMetadata` a required package whenever I'd like `foo` to "do the right thing." I'm not thrilled about requiring …
=> Make `axes` provide defaults for AbstractArray

src/core.jl, test/core.jl
The intended use of this trait is to facilitate extensions of the AxisArrays interface to other AbstractArrays. IMO this is a better approach to https://github.com/JuliaArrays/AxisArrays.jl/pull/45#issue-180968070.
=> Add HasAxes trait

REQUIRE, src/AxisArrays.jl, src/core.jl, test/core.jl, test/runtests.jl
We don't need this anymore. Noticed by @tkelman.
=> Drop the Compat requirement

src/core.jl, test/core.jl
This adds a convenience constructor with the following syntax:
```jl
AxisArray(A::AbstractArray, (names...,), (steps...,), [(offsets...,)])
```
where `steps` is meant in the range-step sense, and `offsets` is like `start` for each coordinate. Requested in https://github.com/timholy/Images.jl/issues/542#issuecomment-270741009. I can add it to ImageAxes but I thought perhaps it would be worth gauging interest here first. CC @tknopp.
Is that one line in the docs enough, or does it need more explanation?
=> Add steps/offsets convenience constructor:

README.md, REQUIRE, src/AxisArrays.jl, src/combine.jl, src/core.jl, src/indexing.jl, src/intervals.jl, src/search.jl, test/REQUIRE, test/indexing.jl, test/readme.jl, test/runtests.jl
I think this gets most of the recent depwarns & breakages. Will require a new Compat tag (https://github.com/JuliaLang/Compat.jl/pull/329). Also doesn't fix
```julia
ArgumentError: colons must be converted by to_indices(...)
Stacktrace:
[1] macro expansion at /home/tim/.julia/v0.6/AxisArrays/src/indexing.jl:47 [inlined]
[2] reaxis at /home/tim/.julia/v0.6/AxisArrays/src/indexing.jl:18 [inlined]
[3] getindex at /home/tim/.julia/v0.6/AxisArrays/src/indexing.jl:52 [inlined]
[4] getindex(::AxisArrays.AxisArray{Float64,2,Array{Float64,2},Tuple{AxisArrays.Axis{:Timestamp,StepRange{DateTime,Base.Dates.Hour}},AxisArrays.Axis{:Cols,Array{Symbol,1}}}}, ::Colon, ::Symbol) at /home/tim/.julia/v0.6/AxisArrays/src/indexing.jl:76
[5] include_from_node1(::String) at ./loading.jl:539
[6] include(::String) …
```
=> Fix 0.6 breakages and depwarns

src/core.jl
Especially since `indices` is used in bounds-checking, this has huge performance consequences.
Fixes https://github.com/JuliaImages/ImageCore.jl/issues/28. CC @Cody-G.
=> Force inlining for `indices` and `size`.

src/core.jl, test/core.jl
Adds methods to `axistrait` and `checkaxis` that accept `Axis` arguments, for consistency with other functions like `axisname` and `axisvalues`.
=> Let axistrait and checkaxis take Axis arguments

src/combine.jl, src/core.jl, test/core.jl
Right now `map` returns a normal Array, discarding the axis data - this PR would change that to preserve axis information, and require that values only be mapped from multiple AxisArrays if they have identical axes. As discussed in #54,  broadcasting with semantic axes is a bit complicated, but `map` seems less controversial?
IIRC back in 0.4 `map` actually preserved the axis data, I guess something in the AbstractArray implementation changed with 0.5? I'm assuming that explicit mapping functions are the best way to regain this behaviour, but if there's a lower-level interface that could be implemented to achieve the same end, that would probably be the more elegant solution.
Also, checking for `matchingdims` was using `size` previously, which caused issues when used with things like …
=> map and map!

src/core.jl, test/core.jl
~~Very curious result if you say `@code_warntype AxisArrays.reduced_indices(axes(A), (1,))`. That's why some of the `@inferred` are commented out.~~
But otherwise this seems to work well.
Oh, argh! I'm running `release-0.5` and this tests on `0.5.0`. This is a problem...
=> Reductions preserve the AxisArray wrapper (fixes #55)

src/combine.jl, test/combine.jl
Fixes issues raised in #64, including a `cat` bug and support for `merge` with range-indexed axes.
=> Fix cat and merge issues

src/combine.jl
This is a rewrite of `merge` and `join` to improve performance by an order of magnitude.
```julia
using AxisArrays
data = randn(400, 100, 50);
A1 = AxisArray(data, Axis{:time}(1:400), Axis{:lon}(1:100), Axis{:lat}(1:50))
A2 = AxisArray(data, Axis{:time}(401:800), Axis{:lon}(1:100), Axis{:lat}(1:50))
```
Master:
```julia
julia> @time merge(A1, A2);
11.517995 seconds (113.78 M allocations: 4.252 GB, 4.12% gc time)
julia> @time join(A1, A2);
15.268915 seconds (131.22 M allocations: 5.025 GB, 4.67% gc time)
```
This PR:
```julia
julia> @time merge(A1, A2);
0.806035 seconds (16.01 M allocations: 1.788 GB, 23.98% gc time)
julia> @time join(A1, A2);
0.838161 seconds (16.01 M allocations: 1.848 GB, 23.06% gc time)
```
=> merge and join speedups

src/combine.jl, src/core.jl, src/indexing.jl, test/indexing.jl
Mostly use dispatch now, except in cases where we change axis names. Fixes a few cases of indexing beyond the dimensionality of the array; it should also be easier to maintain.
=> Refactor reaxis to be slightly less generated

REQUIRE, src/AxisArrays.jl
No longer needed, and it fixes https://github.com/JuliaImages/ImageAxes.jl/issues/18.
=> Remove Iterators from REQUIRES

.gitignore, src/core.jl, src/indexing.jl, src/sortedvector.jl
Adds docs for `axisindexes` and `axistrait`, gets rid of some old `@doc ->` syntax, and updates the `.gitignore` to reflect the actual name of the `docs` folder.
Closes #85
=> Docs for functions related to custom indexing behaviour

test/runtests.jl
We were avoiding this test on 0.6 as there were ambiguities in Base but there is no need for that anymore.
=> Add concrete version bounds to ambiguity test gate

README.md, docs/src/index.md, src/AxisArrays.jl, src/indexing.jl, test/REQUIRE, test/indexing.jl, test/readme.jl
Some comments:
- I think the error message [here](https://github.com/JuliaArrays/AxisArrays.jl/blob/040f11593e6240fc2fb31567fd5ab4b28c0f1f6e/src/indexing.jl#L129) is unreachable. You can see from the order of the if-elseif statements [here](https://github.com/JuliaArrays/AxisArrays.jl/blob/040f11593e6240fc2fb31567fd5ab4b28c0f1f6e/src/indexing.jl#L187) that `axisindexes` with a second argument of type `T <: Real` can’t be called from within `to_index`, since `Real <: Idx`. I have removed the error message. For reals, I think it is more consistent to just let indexing fail than to try and guess if the user was attempting to index by value and throw an error accordingly.
- I don’t understand the definition of `Idx` very well. Why allow `Real` but only `AbstractArray{Int}`? I’m guessing it’s …
=> Implement indexing by value with atvalue

.travis.yml
Nightly is going to be a moving target for a while so we might as well have a green badge for official versions of Julia.
=> Allow failures on nightly

src/categoricalvector.jl, src/combine.jl, src/core.jl, src/indexing.jl, src/intervals.jl, src/search.jl, src/sortedvector.jl, test/indexing.jl
Upgrades all method parameters to `where` syntax and all types from `immutable` to `struct`. It turns out we never make mutable types, which is nice. Also removed the last version check.
=> Upgrade syntax to 1.0-valid constructs (`where` and `struct`)

src/core.jl, test/core.jl
Implements and closes #103
- `AxisArray(A::AxisArray)` is a no-op
- `AxisArray(A::AxisArray, args specifying axis)` wraps `A.data`, rather than A. Furthermore, when axis are missing the default names and indices are taken from A, rather than constructed using `AxisArrays.default_axes`.
=> Constructor over an AxisArray

src/indexing.jl, test/categoricalvector.jl
```
julia> using AxisArrays
julia> using AxisArrays: CategoricalVector
julia> A = AxisArray(zeros(3,3), Axis{:a1}(CategoricalVector([1,55,9])), Axis{:a2}([11,22,33]))
2-dimensional AxisArray{Float64,2,...} with axes:
:a1, [1, 55, 9]
:a2, [11, 22, 33]
And data, a 3×3 Array{Float64,2}:
0.0  0.0  0.0
0.0  0.0  0.0
0.0  0.0  0.0
```
Previously:
```
julia> A[atvalue(55), atvalue(22)]
ERROR: ArgumentError: index Value(55, tol=0) not found
Stacktrace:
[1] axisindexes(::Type{AxisArrays.Categorical}, ::AxisArrays.CategoricalVector{Int64,Array{Int64,1}}, ::AxisArrays.Value{Int64}) at /Users/ericdavies/.julia/v0.6/AxisArrays/src/indexing.jl:249
[2] getindex(::AxisArrays.AxisArray{Float64,2,Array{Float64,2},Tuple{AxisArrays.Axis{:a1,AxisArrays.CategoricalVector{Int64,Array{Int64,1}}},AxisArrays.Axis{: …
```
=> Allow atvalue indexing in categorical axes

README.md, docs/src/index.md, src/indexing.jl, test/indexing.jl
Now that #52 has been merged, this PR attempts to address #84, except for the "by default" part. Simply broadcast `atvalue`:
```
julia> A = AxisArray(rand(7), Axis{:x}(-3:3))
1-dimensional AxisArray{Float64,1,...} with axes:
:x, -3:3
And data, a 7-element Array{Float64,1}:
0.44085 
0.77351 
0.192314
0.904178
0.912603
0.485005
0.730789
julia> A[atvalue.([-2,1])]
1-dimensional AxisArray{Float64,1,...} with axes:
:x, [-2, 1]
And data, a 2-element Array{Float64,1}:
0.77351 
0.912603
```
With many dimensions, I concede that typing `atvalue` repeatedly might become tiresome. Perhaps in some follow-up PR I might implement a macro (`@value`?) for splicing `atvalue` repeatedly into an expression if a user wants to index all dimensions by value. I would guess that should be possible though I …
=> Indexing by an array of values

src/indexing.jl, test/indexing.jl
Previously, it was not possible to force value indexing in all cases without a type check. Now, `atvalue` on non-`Number` types will perform a equality check without expecting tolerance functions to exist. 
In this PR, `Value` becomes an abstract type with subtypes `TolValue` and `ExactValue`.
=> Allow `atvalue` on more types

src/indexing.jl, test/indexing.jl
Previously, logical indexing was only supported on a per-dimension basis. Julia array indexing also allows logical linear indexing, as well as logical indexing with the same dimensionality as the data (treated as linear). AxisArrays provided linear indexing for integers, but not for logicals. Now it supports all the logical indexing that Base supports.
One thing I noticed while making this PR is that linear indexing always produces one axis named `:col`, whereas the first default index name is actually `:row`. But I think if we want to change that, that's another PR.
Closes #110
=> Support logical indexing

src/core.jl, test/core.jl
```julia
C = AxisArray(collect(reshape(1:15,3,5)), Axis{:y}([:a,:b,:c]), Axis{:x}(["a","b","c","d","e"]))
sum(C, Axis{:y}())
sum(C, Axis{:y})
sum(C, (Axis{:y}(), Axis{:x}()))
sum(C, 1)
sum(C, (1,2))
sum(C, (Axis{:y}, Axis{:x}))
```
The last one is due to `typeof((Axis{:y}, Axis{:x})) === Tuple{UnionAll,UnionAll}` which Jeff says is Not A Bug.
This should not affect any cases which already worked and definitely does not affect any cases which were tested.
=> Support reductions over dimensions with non-Number axes

src/indexing.jl, test/indexing.jl, test/runtests.jl
Previously a `A[:, DateTime(2016, 1, 2, 3)]` call which would throw a `BoundsError` from `axisindexes` would throw `BoundsError(4:3, 1)` instead of something referencing the input. 
If anyone has better ideas for testing the contents of an error struct than [this](https://github.com/JuliaArrays/AxisArrays.jl/compare/master...invenia:dimensional-bounds-error?expand=1#diff-a80db444078918d990a564c113253606R192) I'm more than happy to change it.
=> Add and test for a better boundserror when performing implicit value indexing

src/core.jl, src/indexing.jl, test/indexing.jl
Previously, every unknown eltype (not a subtype of Number, AbstractTime, etc.) would require a new `axistrait` definition, or wrapping in a SortedVector or CategoricalVector type.
Now, the default behaviour for indexing using an AbstractArray axis is Categorical, which requires only equality and not `isless`. 
I also made arrays of Value types have the axistrait of either Categorical or Dimensional depending on the type they wrap, which maintains existing tested behaviour.
=> Use categorical indexing behaviour by default for unknown array eltypes

README.md, docs/src/index.md
I was just running through the online examples, and they weren't working because Julia default REPL pasting behaviour was ignoring several lines of code because they didn't start with 'julia>'. Now fixed.
=> Fix README.md so copy and paste works in the REPL

REQUIRE, src/AxisArrays.jl, src/core.jl, src/indexing.jl, src/search.jl
Some new warnings and one error have arisen in 0.7/nightly which break AxisArrays. This fixes them:
- Fix error with 0.7 on Base.Dates - deprecation warning breaks use of Dates.AbstractTime
- Fix warnings with use of Range instead of AbstractRange
- Fix deprecated use of (x...) to (x...,)
Note that there are still some errors in the nightly tests (I'm not sure how to fix them), but there are no longer errors in `using AxisArrays` which was breaking my package!
=> Fix error in nightly with Dates

src/core.jl
In order to include AxisArrays in system images we needed to move the `axisnames` definitions earlier in the core.jl file. This appears to be an issue with generated functions and system images. 
In this case, we're calling the generated `similar` function which references `axisdim` outside of the quote block, which then referenced the `axisnames` methods defined later in the file.
=> Moved axisnames earlier in core.jl

REQUIRE, src/core.jl, src/indexing.jl
Fixes #136 
Before: `214.838 μs (210 allocations: 24.53 KiB)`
After: `24.563 ns (1 allocation: 16 bytes)`
Before: `49.175 ns (1 allocation: 16 bytes)`
After: `42.095 ns (3 allocations: 48 bytes)`
=> Fix performance regression by updating findfirst calls for 0.7

src/combine.jl
Fixes #145 
The existing definition was causing this:
```
julia> cat(dims=1)
0-element Array{Any,1}
```
to become this:
```
julia> cat(dims=1)
ERROR: BoundsError: attempt to access ()
at index [1]
Stacktrace:
[1] getindex(::Tuple{}, ::Int64) at ./tuple.jl:24
[2] _cat at /Users/ericdavies/.julia/dev/AxisArrays/src/combine.jl:20 [inlined]
[3] #cat#44(::Int64, ::Function) at /Users/ericdavies/.julia/dev/AxisArrays/src/combine.jl:16
[4] (::getfield(Base, Symbol("#kw##cat")))(::NamedTuple{(:dims,),Tuple{Int64}}, ::typeof(cat)) at ./none:0
[5] top-level scope at none:0
```
=> Fix type piracy of 0-arg cat

.travis.yml, docs/make.jl, docs/src/index.md, src/core.jl
The documentation build and doctests currently fail, breaking CI. Fix this:
* Add sitename property now required by Documenter
* Fix use of `Base.summary` so that axis type information is readable again.
* Update doctest outputs to the numbers produced in julia 1.0, and the latest version of Unitful.
* Move forward with docs deploy via julia 1.0
=> Fix doctests

.travis.yml
Accidentally broken in 28fdd4e due to weird yaml syntax requirements, but the build passed anyway (!?)
Lets see what Travis has to say.
=> Fix typo in coverage submission

src/core.jl
Iterate over elements in the Axis instead of just returning the axis. Is in line with `axes(Ax) = OneTo(<length of elems>)` and `length(Ax) = <length of elems>`.
Also add `Iterator{Size,Eltype}` traits.
No tests are broken (that worked before).
Does this make sense?
=> Fix iteration over Axis

src/core.jl, src/indexing.jl, test/indexing.jl
Generated functions cannot call any function which might have a method
added after the generated function is defined. This means we need to
hoist such functions outside the generator, either by calling them
beforehand (as we do with axistrait), or ensuring that all methods are
defined before the generator (axisdim).
I belive this fixes #161 (test failures with precompiled-modules=no).
=> Respect generated function invariants

Project.toml
To fix #166 
I believe all changes since 0.3.0 have been bug or infrastructure fixes. The least definitive being #160.
=> Bump version to 0.3.1 for release

src/indexing.jl, test/indexing.jl
AxisArrays has to handle many different index types, but it can't handle types defined in other packages. This provides for a fallback mode in which AxisArrays tries to convert "fancy" index types into "regular" ones, but if this fails then it assumes this is something the parent knows how to handle.
Fixes the following error:
```julia
julia> using AxisArrays, Interpolations
julia> a = AxisArray(1:3, :x)
1-dimensional AxisArray{Int64,1,...} with axes:
:x, Base.OneTo(3)
And data, a 3-element UnitRange{Int64}:
1
2
3
julia> itp = interpolate!(a, BSpline(Linear()));
julia> itp(1.2)
ERROR: MethodError: no method matching isless(::Int64, ::Interpolations.WeightedAdjIndex{2,Float64})
Closest candidates are:
isless(::Missing, ::Any) at missing.jl:66
isless(::Real, ::AbstractFloat) at …
```
=> Try converting indexes once and then defer to the parent

src/indexing.jl
I believe this fixes #169 - looks like I needed an extra an `@inline` in #163
=> Fix performance bug: ensure `to_index` is inlined

src/core.jl, test/core.jl
This adds `first`, `last`, and `step` to the `Axis` interface. The first two were functional before but called `iterate` and `Axis[end]` instead of directly acting on the `val` field. The last method wasn't possible before and now is.
Note: This PR was made in reference to 
- https://github.com/JuliaArrays/AxisArrays.jl/issues/175
- https://github.com/JuliaImages/ImageCore.jl/issues/112
=> Add range interface methods to Axis

Project.toml, README.md, src/core.jl, src/indexing.jl, test/core.jl, test/indexing.jl, test/readme.jl, test/runtests.jl
This adds the following behaviour:
```julia
A = AxisArray(rand(2,5), x=[:a, :b], y=11:15)
A[x=:a]
@btime A[x=:a, y=1] # 5 ns, 0 allocations
```
I think this was discussed somewhere.... only [this comment](https://github.com/JuliaArrays/AxisArrays.jl/pull/152#issuecomment-446571461) perhaps? 
Edit: this also closes #174, because you can write 
```julia
A[x=:b, y=13..14]
A[x=:b, y=atvalue(13)]
```
=> Add keyword indexing + constructor

Project.toml
AxisArrays does not support the latest version of IntervalSets (noticed this due to some issues in Turing, see https://github.com/TuringLang/Turing.jl/issues/683#issuecomment-616412903 and https://github.com/TuringLang/Turing.jl/issues/1220). Maybe it would be a good idea to add CompatHelper?
=> Support IntervalSets 0.5

src/core.jl
for consistency with `AbstractArray` and `AbstractMatrix` and other such types
=> Add AxisMatrix alias
